base.url=https://automationexercise.com/
browser=edge

#register data
register.name=Test
register.email=test
register.title=Mr
register.password=Test@123
register.dob.day=1
register.dob.month=January
register.dob.year=2000
register.firstname=Test
register.lastname=Max
register.company=Test Inc
register.address=9-23 Test Street
register.country=United States
register.state=Test State
register.city=Test City
register.zipcode=546732
register.mobile=9876543210


#Login Data
login.email=test5656@gmail.com
login.password=Test@123
login.invalidemail=test@gmail.com
login.invalidemail=test@gmail.com

#update user data
update.name=Test12
update.title=Ms
update.dob.day=2
update.dob.month=Febraury
update.dob.year=2001
update.firstname=Test12
update.lastname=John
update.company= Veeva 
update.address=hyderabad
update.country=India
update.state=Telangana
update.city=hitech
update.zipcode=123456
update.mobile=1234567890

